apiVersion: skaffold/v2beta11
kind: Config
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: multi-author-blog/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
